### ISSUE TITLE
Graph View: Tool box should be moved up.

### ISSUE THREAD

**Issue by guzman109** [ICICLE-ai/Smartfoodshed_VA_VC1#27]
It is causing the graph view to be pushed down and causing the 'Retrieve' button to not be shown.

![Image](https://user-images.githubusercontent.com/42706936/228898790-9a92f022-fbcc-4bf0-93d0-9fa7f89b87d7.png)

![Image](https://user-images.githubusercontent.com/42706936/228899022-2881218c-3d18-4d87-8b27-3d067ca899cd.png)

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/2d86a084-2460-42aa-8de0-08fdf87f2569)

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/da23de11-8b41-4de5-9e70-8cd2323859fc)

I revised it. Now,  it will change to two rows after zooming into 250% on my laptop.  Please check in your laptop.
