### ISSUE TITLE
"None" should not show up as a node.

### ISSUE THREAD

**Issue by prhuber** [ICICLE-ai/Smartfoodshed_VA_VC1#3]

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/785e31c0-7897-4dd1-bf73-8c26c7018cca)

**Comment by yasmineTYM** [comment]
The  mapping attribute should be "label", not "name"

**Comment by yasmineTYM** [comment]
Once Christian fixed the server, this problem should not exist. I checked the CSFW Wildlife Branch: 


![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/27e0b9e5-e9d1-4296-ba23-741c88be38af)
