### ISSUE TITLE
Reset only resets Tabular View. Does not clear Graph View.

### ISSUE THREAD

**Issue by guzman109** [ICICLE-ai/Smartfoodshed_VA_VC1#30]

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/1397426b-15ab-40e3-9a4f-a24181d3d30c)

**Comment by guzman109** [comment]
I'm reopening this because of the nature of the current reset.

When I load a saved data source, and I expand a new node from the data. If I were to hit reset, it will not reset to the loaded data. It slowly removes nodes until there  are none left.  I think this is due to not selecting any nodes from the table to begin with. I can think of two ways to fix this.

1. Reset the graph view and table view to a blank state. (Change reset to a hard reset)
2. Synchronize the table view to the loaded data in the graph view. (i.e. The saved data that I load should be selected in the table.)

**Comment by yasmineTYM** [comment]
I brought this issue to our teams meeting yesterday. We agreed that the current design is not ituitive. The icon is more like "Undo" operation, which means undo the previous operation.

**Comment by guzman109** [comment]
Undo is a better name!
