### ISSUE TITLE
Initial node placement

### ISSUE THREAD

**Issue by prhuber** [ICICLE-ai/Smartfoodshed_VA_VC1#45]
When an initial node is loaded, it appears just off the upper left corner of the screen. It should be in the center of the screen.

Issue Priority: High

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/7e56c313-b793-44df-97fb-33988c71f85a)
