### ISSUE TITLE
Node color assignment by data class

### ISSUE THREAD

**Issue by prhuber** [ICICLE-ai/Smartfoodshed_VA_VC1#47]
There should be a standard default color scheme for the nodes based on their class (Organization, Program, etc.).

Issue Priority: High

**Comment by yasmineTYM** [comment]
![Image](https://github.com/ICICLE-ai/Smartfoodshed_VA_VC1/assets/18289816/58b7b069-01ad-464f-a62c-49d856f296c9)

Added the automatic detection of node labels, and assign different color to each label.
